server:
  port: 1314 #服务端口
#显示debug级别信息
logging:
  level:
    org.example.controller: debug

spring:
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fschool?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    static-path-pattern: /images/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: F:\experiment2\FamilySchool-backed\fschool\src\main\resources\static

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


